import { ApolloWrapper } from "@/lib/apollo-wrapper";
import "./globals.css";

export const metadata = {
	title: "News + Weather App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html>
			<body>
				<div>
					<ApolloWrapper>{children}</ApolloWrapper>
				</div>
			</body>
		</html>
	);
}
